[package]
name = "localization"
description = "Wheel odometry and pose estimation for bvr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nalgebra = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }
control = { workspace = true }
gps = { workspace = true }



